backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    extension: "md"
    view:
      fields:
        - { label: "Title", name: "title" }
        - { label: "Category", name: "category" }
        - { label: "Date", name: "date" }
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - label: "Category"
        name: "category"
        widget: "select"
        options:
          - { label: "Life", value: "life" }
          - { label: "Faith", value: "faith" }
          - { label: "Essays", value: "essays" }
          - { label: "The Outdoors", value: "the-outdoors" }
          - { label: "Poetry", value: "poetry" }
          - { label: "Reviews", value: "reviews" }
      - { label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", timeFormat: false, default: "{{now}}" }
      - { label: "Excerpt", name: "excerpt", widget: "text", required: false }
      - { label: "Cover Image", name: "coverImage", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
